version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    ports:
      - 3100:3000
      - "8080:8080"
    env_file:
      - .env
    networks:
      - router-network

networks:
  router-network:
    external: true